# Generated by Django 3.0.3 on 2020-02-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('file', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'manager_task',
                'managed': False,
            },
        ),
    ]
