# Generated by Django 3.0.3 on 2020-02-12 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('D', 'Done'), ('U', 'Undone'), ('P', 'In process')], max_length=15)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('file', models.FileField(null=True, upload_to='attachments/')),
            ],
        ),
    ]
