# Generated by Django 3.0.2 on 2020-02-02 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('D', 'Done'), ('U', 'Undone'), ('P', 'In process')], max_length=15)),
                ('deadline', models.DateField(default=datetime.date(2020, 2, 2))),
                ('description', models.TextField()),
            ],
        ),
    ]
