# Generated by Django 3.0.2 on 2020-02-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to='attachments/<django.db.models.fields.CharField>/<django.db.models.fields.DateField>'),
        ),
    ]
